//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.AEPS.WebAdministrative.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Sidebar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Sidebar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.AEPS.WebAdministrative.Resources.Views.Shared._Sidebar", typeof(_Sidebar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string FormsBlocks {
            get {
                return ResourceManager.GetString("FormsBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string FormsForms {
            get {
                return ResourceManager.GetString("FormsForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEPS.
        /// </summary>
        public static string FormsHome {
            get {
                return ResourceManager.GetString("FormsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FormsOptions {
            get {
                return ResourceManager.GetString("FormsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string FormsQuestions {
            get {
                return ResourceManager.GetString("FormsQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string FormsRules {
            get {
                return ResourceManager.GetString("FormsRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        public static string Geography {
            get {
                return ResourceManager.GetString("Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration level 1.
        /// </summary>
        public static string GeographyAdm1 {
            get {
                return ResourceManager.GetString("GeographyAdm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration level 2.
        /// </summary>
        public static string GeographyAdm2 {
            get {
                return ResourceManager.GetString("GeographyAdm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string GeographyCountries {
            get {
                return ResourceManager.GetString("GeographyCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations.
        /// </summary>
        public static string OrganizationAssociations {
            get {
                return ResourceManager.GetString("OrganizationAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string OrganizationPeople {
            get {
                return ResourceManager.GetString("OrganizationPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
