//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.AEPS.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.AEPS.Data.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmBlocksCreated {
            get {
                return ResourceManager.GetString("FrmBlocksCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FrmBlocksDescription {
            get {
                return ResourceManager.GetString("FrmBlocksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FrmBlocksEnable {
            get {
                return ResourceManager.GetString("FrmBlocksEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Id.
        /// </summary>
        public static string FrmBlocksExtId {
            get {
                return ResourceManager.GetString("FrmBlocksExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string FrmBlocksFormsBlock {
            get {
                return ResourceManager.GetString("FrmBlocksFormsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string FrmBlocksFormsBlockNavigation {
            get {
                return ResourceManager.GetString("FrmBlocksFormsBlockNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmBlocksFormsCreated {
            get {
                return ResourceManager.GetString("FrmBlocksFormsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FrmBlocksFormsEnable {
            get {
                return ResourceManager.GetString("FrmBlocksFormsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FrmBlocksFormsForm {
            get {
                return ResourceManager.GetString("FrmBlocksFormsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FrmBlocksFormsFormNavigation {
            get {
                return ResourceManager.GetString("FrmBlocksFormsFormNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string FrmBlocksFormsOrder {
            get {
                return ResourceManager.GetString("FrmBlocksFormsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmBlocksFormsUpdated {
            get {
                return ResourceManager.GetString("FrmBlocksFormsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmBlocksId {
            get {
                return ResourceManager.GetString("FrmBlocksId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrmBlocksName {
            get {
                return ResourceManager.GetString("FrmBlocksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string FrmBlocksRepeat {
            get {
                return ResourceManager.GetString("FrmBlocksRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string FrmBlocksTimes {
            get {
                return ResourceManager.GetString("FrmBlocksTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FrmBlocksTitle {
            get {
                return ResourceManager.GetString("FrmBlocksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmBlocksUpdated {
            get {
                return ResourceManager.GetString("FrmBlocksUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmFormsCreated {
            get {
                return ResourceManager.GetString("FrmFormsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FrmFormsDescription {
            get {
                return ResourceManager.GetString("FrmFormsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FrmFormsEnable {
            get {
                return ResourceManager.GetString("FrmFormsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Id.
        /// </summary>
        public static string FrmFormsExtId {
            get {
                return ResourceManager.GetString("FrmFormsExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmFormsId {
            get {
                return ResourceManager.GetString("FrmFormsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrmFormsName {
            get {
                return ResourceManager.GetString("FrmFormsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string FrmFormsSettingsApp {
            get {
                return ResourceManager.GetString("FrmFormsSettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmFormsSettingsCreated {
            get {
                return ResourceManager.GetString("FrmFormsSettingsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FrmFormsSettingsForm {
            get {
                return ResourceManager.GetString("FrmFormsSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form settings.
        /// </summary>
        public static string FrmFormsSettingsFormsNavigation {
            get {
                return ResourceManager.GetString("FrmFormsSettingsFormsNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmFormsSettingsId {
            get {
                return ResourceManager.GetString("FrmFormsSettingsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrmFormsSettingsName {
            get {
                return ResourceManager.GetString("FrmFormsSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmFormsSettingsUpdated {
            get {
                return ResourceManager.GetString("FrmFormsSettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FrmFormsSettingsValue {
            get {
                return ResourceManager.GetString("FrmFormsSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FrmFormsTitle {
            get {
                return ResourceManager.GetString("FrmFormsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmFormsUpdated {
            get {
                return ResourceManager.GetString("FrmFormsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmOptionsCreated {
            get {
                return ResourceManager.GetString("FrmOptionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FrmOptionsEnable {
            get {
                return ResourceManager.GetString("FrmOptionsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Id.
        /// </summary>
        public static string FrmOptionsExtId {
            get {
                return ResourceManager.GetString("FrmOptionsExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmOptionsId {
            get {
                return ResourceManager.GetString("FrmOptionsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string FrmOptionsLabel {
            get {
                return ResourceManager.GetString("FrmOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrmOptionsName {
            get {
                return ResourceManager.GetString("FrmOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string FrmOptionsQuestion {
            get {
                return ResourceManager.GetString("FrmOptionsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string FrmOptionsQuestionNavigation {
            get {
                return ResourceManager.GetString("FrmOptionsQuestionNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmOptionsUpdated {
            get {
                return ResourceManager.GetString("FrmOptionsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string FrmQuestionsBlock {
            get {
                return ResourceManager.GetString("FrmQuestionsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string FrmQuestionsBlockNavigation {
            get {
                return ResourceManager.GetString("FrmQuestionsBlockNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string FrmQuestionsCreated {
            get {
                return ResourceManager.GetString("FrmQuestionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FrmQuestionsDescription {
            get {
                return ResourceManager.GetString("FrmQuestionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FrmQuestionsEnable {
            get {
                return ResourceManager.GetString("FrmQuestionsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern Id.
        /// </summary>
        public static string FrmQuestionsExtId {
            get {
                return ResourceManager.GetString("FrmQuestionsExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmQuestionsId {
            get {
                return ResourceManager.GetString("FrmQuestionsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string FrmQuestionsLabel {
            get {
                return ResourceManager.GetString("FrmQuestionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FrmQuestionsName {
            get {
                return ResourceManager.GetString("FrmQuestionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string FrmQuestionsOrder {
            get {
                return ResourceManager.GetString("FrmQuestionsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string FrmQuestionsRulesApp {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FrmQuestionsRulesId {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FrmQuestionsRulesMessage {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string FrmQuestionsRulesQuestion {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string FrmQuestionsRulesQuestionsNavigation {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesQuestionsNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string FrmQuestionsRulesRule {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of rule.
        /// </summary>
        public static string FrmQuestionsRulesType {
            get {
                return ResourceManager.GetString("FrmQuestionsRulesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of question.
        /// </summary>
        public static string FrmQuestionsType {
            get {
                return ResourceManager.GetString("FrmQuestionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string FrmQuestionsUpdated {
            get {
                return ResourceManager.GetString("FrmQuestionsUpdated", resourceCulture);
            }
        }
    }
}
